Added oak-d-cm4 eeprom files
luxonis/depthai-boards pull request #10
Opened 2023-02-16 11:57 UTC by njezersek

2023-02-17 23:37 UTC, themarpe approved these changes

2023-02-20 13:26 UTC, Luxonis-David requested changes
Added few comments requesting changes

2023-02-20 13:26 UTC, Luxonis-David commented on batch/eeprom/DM2097_R1M1E1_oak_d_cm4_poe.json
> +    "boardRev": "R1M1E1",
Change revision to: R3M1E4

2023-02-20 13:26 UTC, Luxonis-David commented on boards/OAK-D-CM4-POE-C11.json
> +        "name": "OAK-D-CM4-C11",
change to OAK-D-CM4-PoE-C11

2023-02-20 13:26 UTC, Luxonis-David commented on batch/oak_d_cm4.json
> +			"title": "OAK-D CM4 PoE (DM2097 R1M1E1)",
HW revision R3M1E4

2023-02-20 13:26 UTC, Luxonis-David commented on boards/OAK-D-CM4-POE-C11.json
> +                "hfov": 80.0,
OAK-D-CM4-POE-C11 (w/OV9782) HFOV is the same as stereo HFOV so I suppose 71.86°

2023-02-20 14:09 UTC, merged