New boards
luxonis/depthai-boards pull request #25
Opened 2023-03-24 06:49 UTC by njezersek

- OAK-FFC 4P (DD2090 R7M1E7)

2023-03-24 07:05 UTC, Luxonis-David requested changes

2023-03-24 07:05 UTC, Luxonis-David commented on batch/eeprom/DD2090_R7M1E7_oak_ffc_4p.json
> +    "boardOptions": 3,
```suggestion
    "boardOptions": 0,
```

2023-03-24 07:05 UTC, Luxonis-David commented on batch/eeprom/DD2090_R7M1E7_oak_ffc_4p.json
> +    "hardwareConf": "F0-FV00-BC001",
```suggestion
    "hardwareConf": "F0-FV00-BC000",
```

2023-03-27 11:57 UTC, themarpe approved these changes
LGTM

2023-03-27 12:10 UTC, Luxonis-David approved these changes

2023-03-27 12:13 UTC, merged